### ISSUE TITLE
Using poetry scripts option

### ISSUE THREAD

**Issue by reo6** [DrShahinstein/cboard#1]
Hey!

You can use Poetry's [script](https://python-poetry.org/docs/pyproject/#scripts) option for the pyproject.toml file. Thus, installing the package with pip creates a script in ``.local/bin`` and you can call the script without the ``python -m`` prefix.

```toml
[tool.poetry.scripts]
cboard = 'cboard:main'
```

(I'd tell you in the chat but you would forget, now you can't close this issue without solving this :smiling_imp: )
